version: '3.4'

services:
  nhom:
    image: nhom
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - db
      - redis
      - elasticsearch

  db:
    image: postgres:14
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: Aa123456
      POSTGRES_DB: DjangoDB
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.10.2
    environment:
      discovery.type: single-node
      xpack.security.enabled: "false"
    ports:
      - "9200:9200"
volumes:
  db_data:
